# Generated by Django 4.0.5 on 2022-07-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время приема')),
                ('note', models.TextField(verbose_name='Заметка')),
            ],
        ),
        migrations.CreateModel(
            name='GroupService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('type', models.CharField(max_length=1, verbose_name='Тип операции')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('info', models.TextField(verbose_name='Дополнительная информация')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время заявки')),
                ('processed', models.BooleanField(default=False, verbose_name='Заявка обработана')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='Цена')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.groupservice', verbose_name='Группа услуг')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='UserAIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_day',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='WhoViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.requestservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.invoicematerial', verbose_name='Код расхода материала')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.customerreception', verbose_name='Код приема')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.typeoftool', verbose_name='Тип инструмента')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Стоимость')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.customerreception', verbose_name='Код приема')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.service', verbose_name='Код услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Подпись')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ais.userais')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_before', models.ImageField(upload_to='', verbose_name='Фото до')),
                ('photo_after', models.ImageField(upload_to='', verbose_name='Фото после')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.typeofmaterial', verbose_name='Тип материала')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('type', models.CharField(max_length=1, verbose_name='Тип операции')),
                ('date', models.DateField(verbose_name='Дата')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais')),
            ],
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.material'),
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais'),
        ),
        migrations.AddField(
            model_name='customerreception',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='customerreception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.userais'),
        ),
    ]
