# Generated by Django 4.0.5 on 2022-08-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_customerreception_groupservice_invoicematerial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhoViewed',
        ),
    ]
