# Generated by Django 4.0.5 on 2022-08-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0004_groupservice_num_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('address', models.CharField(max_length=100, verbose_name='Улица - Дом')),
                ('phone_one', models.CharField(max_length=12, verbose_name='Телефон 1')),
                ('phone_two', models.CharField(max_length=12, verbose_name='Телефон 2')),
                ('schedule_days', models.CharField(max_length=20, verbose_name='График работы - дни')),
                ('schedule_hours', models.CharField(max_length=20, verbose_name='График работы - часы')),
            ],
        ),
    ]
