# Generated by Django 4.0.5 on 2022-08-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0005_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
