# Generated by Django 4.0.5 on 2022-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0006_delete_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_after',
            field=models.ImageField(upload_to='photo_works/', verbose_name='Фото после'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_before',
            field=models.ImageField(upload_to='photo_works/', verbose_name='Фото до'),
        ),
    ]
