# Generated by Django 4.0.5 on 2022-08-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0007_alter_photo_photo_after_alter_photo_photo_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
