# Generated by Django 4.0.5 on 2022-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0008_remove_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
