# Generated by Django 4.0.5 on 2022-09-02 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0010_alter_servicesprovided_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreception',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 22, 46, 38, 19778), verbose_name='Дата и время приема'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 22, 46, 38, 16786), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 22, 46, 38, 15753), verbose_name='Дата и время заявки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 22, 46, 38, 16786), verbose_name='Дата и время'),
        ),
    ]
