# Generated by Django 4.0.5 on 2022-09-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0011_alter_customerreception_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetool',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='invoicetool',
            name='user',
        ),
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usedmaterial',
            name='material_invoice',
        ),
        migrations.RemoveField(
            model_name='usedmaterial',
            name='reception',
        ),
        migrations.AlterField(
            model_name='customerreception',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 23, 10, 4, 592009), verbose_name='Дата и время приема'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 23, 10, 4, 590976), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 23, 10, 4, 589979), verbose_name='Дата и время заявки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 23, 10, 4, 592009), verbose_name='Дата и время'),
        ),
        migrations.DeleteModel(
            name='InvoiceMaterial',
        ),
        migrations.DeleteModel(
            name='InvoiceTool',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='TypeOfMaterial',
        ),
        migrations.DeleteModel(
            name='TypeOfTool',
        ),
        migrations.DeleteModel(
            name='UsedMaterial',
        ),
    ]
